name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libstdc++6 liblzma5 libbz2-1.0 bioperl samtools freebayes bcftools

    - name: Add binaries to PATH
      run: |
        echo "$PWD/bin:$PWD/binaries/noarch:$PWD/binaries/linux" >> $GITHUB_PATH

    - name: Check snippy versions and configurations
      run: |
        snippy --version
        snippy --check
        snippy-core --version
        snippy-core --check

    - name: Run tests
      run: |
        make -C test

