name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: snippy-env
        channels: conda-forge,bioconda,defaults
        channel-priority: strict

    - name: Install Dependencies
      shell: bash -el {0}
      run: |
        conda install -y \
          samtools bcftools freebayes bedtools \
          bwa minimap2 parallel vcflib vt snpeff \
          seqtk snp-sites wgsim any2fasta \
          perl-bioperl samclip

    - name: Add binaries to PATH
      shell: bash -el {0}
      run: |
        echo "$PWD/bin:$PWD/binaries/noarch:$PWD/binaries/linux" >> $GITHUB_PATH

    - name: Check snippy versions and configurations
      shell: bash -el {0}
      run: |
        snippy --version
        snippy --check
        snippy-core --version
        snippy-core --check

    - name: Run tests
      shell: bash -el {0}
      run: |
        make -C test

